#!/bin/bash

######################################################################
#
# Remove all assembled jars on all nodes
#
######################################################################

# Set CLUSTER_NR to the number of the cluster you're working with
CLUSTER_NR_SEL=${CLUSTER_NR:?Set environment variable CLUSTER_NR to your cluster number}

CLUSTER_BASE_NODE_NR=$(expr $CLUSTER_NR_SEL \* 5)

PI_USER=akkapi
ALL_NODES="0 1 2 3 4"
SELECTED_NODE=$2
NODES=${SELECTED_NODE:-$ALL_NODES}

for i in $NODES;do
  node=$[ CLUSTER_BASE_NODE_NR + i ]
  echo "Clearing jars on node-${node}"
  ssh ${PI_USER}@node-${node} "sudo rm *.jar"
done
