#!/bin/bash

######################################################################
#
# Remove all assembled jars on all nodes or a selected node
#
# Usage:
#   ./clrJars [node-nr]
#
# Set CLUSTER_NR to the number of the cluster you're working with
# Default value of CLUSTER_NR is 0
######################################################################

# Set CLUSTER_NR to the number of the cluster you're working with
CLUSTER_NR_SEL=${CLUSTER_NR:-0}

CLUSTER_BASE_NODE_NR=$(expr $CLUSTER_NR_SEL \* 5)

PI_USER=akkapi
ALL_NODES="0 1 2 3 4"

SELECTED_NODE=$1
NODES=${SELECTED_NODE:-$ALL_NODES}

for i in $NODES;do
  node=$[ CLUSTER_BASE_NODE_NR + i ]
  account=${PI_USER}@node-${node}
  echo "Clearing jars/exercises on node-${node}"
  ssh $account "sudo rm -rf *.jar exercises"
done
