#!/bin/bash

PI_USER=akkapi
EXERCISE_NR=`printf %03d $1`
FATJAR=`ls exercise*${EXERCISE_NR}*/target/scala-2.12/exercise*${EXERCISE_NR}*jar`
ALL_NODES="0 1 2 3 4 5"
SELECTED_NODE=$2
NODES=${SELECTED_NODE:-$ALL_NODES}
echo "Using $FATJAR"

for i in $NODES;do
  echo "Copy $FATJAR to node-${i}"
  scp $FATJAR ${PI_USER}@node-${i}:/home/${PI_USER}
done

