#!/bin/bash

FATJAR=exercise_006_split_brain_resolver_keep_referee/target/scala-2.12/exercise_006_split_brain_resolver_keep_referee-assembly-1.3.0.jar

for i in 0 1 2 3 4;do
  scp $FATJAR pirate@node-${i}:/home/pirate
done

