#!/bin/bash

for i in 0 1 2 3 4;do
  scp exercise_004_cluster_state_monitor_improved/target/scala-2.12/exercise_004_cluster_state_monitor_improved-assembly-1.3.0.jar pirate@node-${i}:/home/pirate
done

