#!/bin/bash

FATJAR=exercise_003_cluster_weakly_up_disabled/target/scala-2.12/exercise_003_cluster_weakly_up_disabled-assembly-1.3.0.jar

for i in 0 1 2 3 4;do
  scp $FATJAR pirate@node-${i}:/home/pirate
done

