#!/bin/bash

# Set CLUSTER_NR to the number of the cluster you're working with
CLUSTER_NR_SEL=${CLUSTER_NR:?Set environment variable CLUSTER_NR to your cluster number}

CLUSTER_BASE_NODE_NR=$(expr $CLUSTER_NR_SEL \* 5)

PI_USER=akkapi
ALL_NODES="0 1 2 3 4"
SELECTED_NODE=$2
NODES=${SELECTED_NODE:-$ALL_NODES}

for i in $NODES;do
  node=$[ CLUSTER_BASE_NODE_NR + i ]
  echo "getting logs from node-${node}"
  scp ${PI_USER}@node-${node}:/home/${PI_USER}/neopixel.log collectedLogs/node-${node}.log
done
