#!/bin/bash

######################################################################
#
# Retrieve the log file from all nodes or a specific node
#
# Usage:
#   ./getLogs [node-nr]
#
# Set CLUSTER_NR to the number of the cluster you're working with
# Default value of CLUSTER_NR is 0
######################################################################

CLUSTER_NR_SEL=${CLUSTER_NR:-0}

COLLECT_BASEDIR=collectedLogs
CLUSTER_BASE_NODE_NR=$(expr $CLUSTER_NR_SEL \* 5)

PI_USER=akkapi
ALL_NODES="0 1 2 3 4"
SELECTED_NODE=$1
NODES=${SELECTED_NODE:-$ALL_NODES}

mkdir -p $COLLECT_BASEDIR

for i in $NODES;do
  node=$[ CLUSTER_BASE_NODE_NR + i ]
  echo "getting logs from node-${node}"
  scp ${PI_USER}@node-${node}:/home/${PI_USER}/neopixel.log ${COLLECT_BASEDIR}/node-${node}.log
done
