#!/bin/bash

##################################################
# Run this script on a PI node with the exercise
# number as a single argument
#
# Example: ./run 7
#
##################################################

EXERCISE_NR=`printf %03d $1`
FATJAR=`ls exercise*${EXERCISE_NR}*jar`
NODE=`hostname`

echo "Running $FATJAR on $NODE"

sudo pkill -SIGKILL -f "exercise.*_[0-9][0-9][0-9]_.*"

sudo java -Djava.library.path=.  -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dakka.remote.netty.tcp.port=2550 -Dakka.remote.netty.tcp.hostname=$NODE -jar $FATJAR com.neopixel.ClusterStatusTrackerMain
