#!/bin/bash

##################################################
# Run this script on a PI node with the exercise
# number as a single argument
#
# Example: ./run 7
#
##################################################

EXERCISE_NR=`printf %03d $1`
FATJAR=`ls exercise*${EXERCISE_NR}*jar`
CINNAMON="cinnamon-agent.jar"
NODE=`hostname`

echo "Running $FATJAR on $NODE"

sudo pkill -SIGKILL -f "exercise.*_[0-9][0-9][0-9]_.*"

shift

echo "$@"

sudo java -javaagent:$CINNAMON -Djava.library.path=.  -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcluster-node-configuration.node-hostname=$NODE -jar $FATJAR "com.neopixel.ClusterStatusTrackerMain $@"
