# Scrape configuration for default Cinnamon Prometheus HTTP Server on localhost
scrape_configs:
  - job_name: 'cinnamon'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:9001',
                  'node-0:9001',
                  'node-1:9001',
                  'node-2:9001',
                  'node-3:9001',
                  'node-4:9001']
