#!/bin/bash

######################################################################
# Run this script on a PI node with the exercise number as a single argument
#
# Example: ./run 7
#
######################################################################

EXERCISE_NR=$(printf %03d $1 2>/dev/null)
EXERCISE_FOLDER=$(cd exercises 2>/dev/null;  ls -d exercise*${EXERCISE_NR}* 2>/dev/null)
# Check if an exercise was found with the given number, otherwise exit
if [ "Empty$EXERCISE_FOLDER" == "Empty" ]; then
	echo "No exercise found with exercise number $1"
  exit -1
fi

EXERCISE_RUNSCRIPT=$(cd exercises/$EXERCISE_FOLDER/bin && ls |grep -v .bat)
NODE=`hostname`

echo "Running $EXERCISE_RUNSCRIPT on $NODE"

sudo pkill -SIGKILL -f "exercise.*_[0-9][0-9][0-9]_.*"

shift

if [ -f setLedType ];then
  . ./setLedType
fi

if [ -f $CINNAMON ];then
  CINNAMON_AGENT="-javaagent:$CINNAMON"
fi

LedStripType=${LED_STRIP_TYPE:-eight-led-reversed-order}

(cd exercises/$EXERCISE_FOLDER && sudo bin/$EXERCISE_RUNSCRIPT -Dcluster-node-configuration.node-hostname=$NODE -Dcluster-status-indicator.led-strip-type=$LED_STRIP_TYPE)
