#!/bin/bash

######################################################################
# Run this script on a PI node with the exercise number as a single argument
#
# Example: ./run 7
#
######################################################################

EXERCISE_NR=$(printf %03d $1 2>/dev/null)

# As the exercise is unzipped in the background (see copy command for details),
# it is necessary to check if 'unzip' command is still running, if it is, try
# again in a second... We know that 'unzip' is finished when the zip archive
# is gone (it is deleted by the 'copy' script
while [ -f exercises/exercise*${EXERCISE_NR}*.zip ];do 
  sleep 1
done

EXERCISE_FOLDER=$(cd exercises 2>/dev/null;  ls -d exercise*${EXERCISE_NR}* 2>/dev/null)
# Check if an exercise was found with the given number, otherwise exit
if [ "Empty$EXERCISE_FOLDER" == "Empty" ]; then
	echo "No exercise found with exercise number $1"
  exit -1
fi

EXERCISE_RUNSCRIPT=$(cd exercises/$EXERCISE_FOLDER/bin && ls |grep -v .bat)
NODE=`hostname`

echo "Running $EXERCISE_RUNSCRIPT on $NODE"

sudo pkill -SIGKILL -f "exercise.*_[0-9][0-9][0-9]_.*"

shift

if [ -f setLedType ];then
  . ./setLedType
fi

LedStripType=${LED_STRIP_TYPE:-eight-led-reversed-order}

(cd exercises/$EXERCISE_FOLDER && sudo bin/$EXERCISE_RUNSCRIPT -Dcluster-node-configuration.node-hostname=$NODE -Dakka.management.http.hostname=$NODE -Dcluster-status-indicator.led-strip-type=$LED_STRIP_TYPE)
