/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package neopixel;

public interface rpi_ws281xConstants {
  public final static int WS2811_TARGET_FREQ = rpi_ws281xJNI.WS2811_TARGET_FREQ_get();
  public final static int SK6812_STRIP_RGBW = rpi_ws281xJNI.SK6812_STRIP_RGBW_get();
  public final static int SK6812_STRIP_RBGW = rpi_ws281xJNI.SK6812_STRIP_RBGW_get();
  public final static int SK6812_STRIP_GRBW = rpi_ws281xJNI.SK6812_STRIP_GRBW_get();
  public final static int SK6812_STRIP_GBRW = rpi_ws281xJNI.SK6812_STRIP_GBRW_get();
  public final static int SK6812_STRIP_BRGW = rpi_ws281xJNI.SK6812_STRIP_BRGW_get();
  public final static int SK6812_STRIP_BGRW = rpi_ws281xJNI.SK6812_STRIP_BGRW_get();
  public final static int SK6812_SHIFT_WMASK = rpi_ws281xJNI.SK6812_SHIFT_WMASK_get();
  public final static int WS2811_STRIP_RGB = rpi_ws281xJNI.WS2811_STRIP_RGB_get();
  public final static int WS2811_STRIP_RBG = rpi_ws281xJNI.WS2811_STRIP_RBG_get();
  public final static int WS2811_STRIP_GRB = rpi_ws281xJNI.WS2811_STRIP_GRB_get();
  public final static int WS2811_STRIP_GBR = rpi_ws281xJNI.WS2811_STRIP_GBR_get();
  public final static int WS2811_STRIP_BRG = rpi_ws281xJNI.WS2811_STRIP_BRG_get();
  public final static int WS2811_STRIP_BGR = rpi_ws281xJNI.WS2811_STRIP_BGR_get();
  public final static int WS2812_STRIP = rpi_ws281xJNI.WS2812_STRIP_get();
  public final static int SK6812_STRIP = rpi_ws281xJNI.SK6812_STRIP_get();
  public final static int SK6812W_STRIP = rpi_ws281xJNI.SK6812W_STRIP_get();
}
