/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package neopixel;

public class SWIGTYPE_p_ws2811_device {
  private transient long swigCPtr;

  protected SWIGTYPE_p_ws2811_device(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_ws2811_device() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_ws2811_device obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

